version: '3.8'

services:
  k6-load-test:
    image: grafana/k6:latest
    stdin_open: true  # equivalent to -i flag
    network_mode: host  # equivalent to --network="host"
    environment:
      - BASE_URL=${BASE_URL:-http://host.docker.internal:8080}
    volumes:
      - .:/k6 
    working_dir: /k6
    command: [
      "run",
      "--out=influxdb=http://localhost:8086/k6",
      "k6_loadtesting.js"
    ]
    profiles:
      - load-test
